server:
  port: 8030
spring:
  application:
    name: order
  datasource:
    name: order_system
    url: jdbc:mysql://localhost:3306/order_system?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 110518
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.entity
